git update-index --assume-unchanged docroot/update.php
git update-index --assume-unchanged docroot/.csslintrc
git update-index --assume-unchanged docroot/.editorconfig
git update-index --assume-unchanged docroot/.eslintignore
git update-index --assume-unchanged docroot/.eslintrc
git update-index --assume-unchanged docroot/.eslintrc.json
git update-index --assume-unchanged docroot/.ht.router.php
git update-index --assume-unchanged docroot/.htaccess
git update-index --assume-unchanged docroot/README.md
git update-index --assume-unchanged docroot/autoload.php
git update-index --assume-unchanged docroot/config/.gitkeep
git update-index --assume-unchanged docroot/drush/README.md
git update-index --assume-unchanged docroot/drush/drush.yml
git update-index --assume-unchanged docroot/drush/sites/default.site.yml
git update-index --assume-unchanged docroot/index.php
git update-index --assume-unchanged docroot/modules/custom/README.md
git update-index --assume-unchanged docroot/profiles/custom/README.md
git update-index --assume-unchanged docroot/profiles/custom/unicef_profile/README.md
git update-index --assume-unchanged docroot/profiles/custom/unicef_profile/unicef_profile.info.yml
git update-index --assume-unchanged docroot/profiles/custom/unicef_profile/unicef_profile.install
git update-index --assume-unchanged docroot/profiles/custom/unicef_profile/unicef_profile.profile
git update-index --assume-unchanged docroot/simplesamlphp/.gitkeep
git update-index --assume-unchanged docroot/sites/blt.development.services.yml
git update-index --assume-unchanged docroot/sites/default/blt.yml
git update-index --assume-unchanged docroot/sites/default/default.local.drush.yml
git update-index --assume-unchanged docroot/sites/default/default.services.yml
git update-index --assume-unchanged docroot/sites/default/default.settings.php
git update-index --assume-unchanged docroot/sites/default/services.yml
git update-index --assume-unchanged docroot/sites/default/settings.php
git update-index --assume-unchanged docroot/sites/default/settings/default.local.settings.php
git update-index --assume-unchanged docroot/sites/development.services.yml
git update-index --assume-unchanged docroot/sites/example.settings.local.php
git update-index --assume-unchanged docroot/sites/example.sites.php
git update-index --assume-unchanged docroot/sites/lightning.extend.yml
git update-index --assume-unchanged docroot/sites/services.yml
git update-index --assume-unchanged docroot/sites/sites.php
git update-index --assume-unchanged docroot/tests/README.md
git update-index --assume-unchanged docroot/tests/behat/behat.yml
git update-index --assume-unchanged docroot/tests/behat/example.local.yml
git update-index --assume-unchanged docroot/tests/behat/features/Examples.feature
git update-index --assume-unchanged docroot/tests/behat/features/bootstrap/Drupal/FeatureContext.php
git update-index --assume-unchanged docroot/tests/phpunit/ExampleTest.php
git update-index --assume-unchanged docroot/tests/phpunit/phpunit.xml
git update-index --assume-unchanged docroot/themes/custom/README.md
