#!/usr/bin/env bash

set -ev

if [ $TRAVIS_PULL_REQUEST != "false" ]; then
	PR_OWNER=${TRAVIS_PULL_REQUEST_SLUG%/*}
	if [[ $TRAVIS_COMMIT_MESSAGE =~ "[skip deployment]" ]] ;
	then
	  echo "Skipping deployment"
	  touch ${BUILD_DIR}/hooks/skip_deployment
	  blt artifact:deploy --commit-msg "Automated commit by Travis CI for Build ${TRAVIS_BUILD_ID} [skip deployment]" --branch "${PR_OWNER}-${TRAVIS_PULL_REQUEST}-${TRAVIS_BRANCH}-build" --ignore-dirty --no-interaction -v
	else
	  blt artifact:deploy --commit-msg "Automated commit by Travis CI for Build ${TRAVIS_BUILD_ID}" --branch "${PR_OWNER}-${TRAVIS_PULL_REQUEST}-${TRAVIS_BRANCH}-build" --ignore-dirty --no-interaction -v
	fi
fi

set +v
