#!/usr/bin/env bash

set -ev

if [[ $TRAVIS_COMMIT_MESSAGE =~ "[skip deployment]" ]] ;
then
  echo "Skipping deployment"
  touch ${BUILD_DIR}/hooks/skip_deployment
  blt artifact:deploy --commit-msg "Automated commit by Travis CI for Build ${TRAVIS_TAG} [skip deployment]" --tag "${TRAVIS_TAG}-build" --ignore-dirty --no-interaction -v
else
  blt artifact:deploy --commit-msg "Automated commit by Travis CI for Build ${TRAVIS_TAG}" --tag "${TRAVIS_TAG}-build" --ignore-dirty --no-interaction -v
fi

set +v
