<?php

/**
 * @file
 * Contains course.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @var array
 */
const COURSE_FORMS = [
  'node_course_form',
  'node_course_edit_form',
];

/**
 * Implements hook_help().
 */
function course_help(string $route_name, RouteMatchInterface $route_match): string {
  switch ($route_name) {
    // Main module help for the user module.
    case 'help.page.user':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom module to make changes in Course content type.') . '</p>';
      return $output;

    default:
  }

  return '';
}

/**
 * Implements hook_form_alter().
 */
function course_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  if (in_array($form_id, COURSE_FORMS)) {
    $form['#attached']['library'][] = 'course/course.form';
    $form['#validate'][] = 'course_validate_form';
    $form['field_course_location']['widget'][0]['top'] = [];
    $form['field_course_tags']['widget']['add_more']['#value'] = t('Add new tag');
    $form['field_course_tags']['widget']['add_more']['#prefix'] = '<div class="course-tags-content"><i class="ph-plus"></i>';
    $form['field_course_tags']['widget']['add_more']['#sufix'] = '</div>';
  }
}

/**
 * Validate course form.
 * @var array $form
 * @var \Drupal\Core\Form\FormStateInterface $form_state
 */
function course_validate_form(array &$form, FormStateInterface $form_state): void {
  /** @var \Drupal\course\Service\CourseFormValidator */
  $form_validator = \Drupal::service('course.form_validator');
  $form_validator->validateCourse($form_state);
}
